import { Box, ChakraProvider, Container } from "@chakra-ui/react";
import theme from "../../libs/theme";
import Footer from "./Footer";
import Navbar from "../NavBar";
import { AnimatePresence } from "framer-motion";
import { Router } from "next/router";
import Head from "next/head";
import dynamic from "next/dynamic";

type CommonLayoutProps = {
  children: React.ReactElement;
  router: Router;
};

function CommonLayout({ children, router }: CommonLayoutProps) {
  return (
    <Box as="main" pb={8}>
      <Head>
        <title>Tuấn Xinh Trai - Homepage</title>
        <meta name="viewport" content="width=device-with, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChakraProvider theme={theme}>
        <Navbar  />

        <Container maxW="container.md" pt={14}>
          <AnimatePresence
            exitBeforeEnter
            initial={true}
            onExitComplete={() => {
              if (typeof window !== "undefined") {
                window.scrollTo({ top: 0 });
              }
            }}
          >
            {children}
            <Footer />
          </AnimatePresence>
        </Container>
      </ChakraProvider>
    </Box>
  );
}

export default CommonLayout;